# Generated by Django 3.0.6 on 2020-05-08 11:03

import accounts.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=255)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('anonymous', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=64)),
                ('enforce_limits', models.BooleanField(default=True)),
                ('group_code_override', models.BooleanField(default=False)),
                ('admin_report_override', models.BooleanField(default=False)),
                ('report_branding', models.BooleanField(default=False)),
                ('site_branding', models.BooleanField(default=False)),
                ('player_pays', models.BooleanField(default=False)),
                ('anonymous_games', models.BooleanField(default=False)),
                ('show_next_steps', models.BooleanField(default=True)),
                ('report_end', models.FileField(blank=True, upload_to=accounts.models.Account.report_end_upload_path)),
                ('hide_player_reports', models.BooleanField(default=False)),
                ('player_report_alt_message', models.TextField(default='')),
                ('admin', models.BooleanField(default=False)),
                ('language', models.CharField(default='', max_length=5)),
                ('extra_languages', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cardset', models.CharField(max_length=16)),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('total', models.PositiveIntegerField()),
                ('used', models.PositiveIntegerField(default=0)),
                ('anonymous', models.BooleanField(default=False)),
                ('enforce_referrer', models.BooleanField(default=False)),
                ('referrer_urls', models.TextField(default='[]')),
                ('individual', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cover_text', models.TextField(default='{}')),
                ('cover_image', models.ImageField(blank=True, upload_to=accounts.models.Branding.cover_image_upload_path)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableGames',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_games', to='accounts.Account')),
            ],
        ),
    ]
