# Generated by Django 3.0.6 on 2020-05-08 11:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('active_until', models.DateTimeField()),
                ('stripe_subscription_id', models.CharField(max_length=64)),
                ('stripe_plan_id', models.CharField(max_length=255)),
                ('stripe_plan_name', models.CharField(max_length=255)),
                ('group_codes', models.BooleanField(default=False)),
                ('admin_reports', models.BooleanField(default=False)),
                ('manual_override', models.BooleanField(default=False)),
                ('interval', models.CharField(max_length=255)),
                ('games', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('active_until', models.DateTimeField()),
                ('stripe_product_id', models.CharField(max_length=255)),
                ('stripe_product_name', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.Account')),
            ],
        ),
    ]
